#logging:
#  level:
#    org: DEBUG
#    com: DEBUG
spring:
  profiles:
    active: prod
server:
  port: 9000

---
# Настройки по умолчанию для всех профилей
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# Настройки для профиля local
---
spring:
  config:
    activate:
      on-profile: local
  logging:
    level:
      org.hibernate: DEBUG
  h2:
    console:
      enabled: true
      settings:
        trace: on
  sql:
    init:
      mode: always
      data-locations: classpath:data-h2.sql
      schema-locations: classpath:schema-h2.sql

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: false
    show-sql: true
    hibernate:
      id:
        new_generator_mappings: true
      ddl-auto: none # Этот параметр указывает Hibernate не выполнять автоматическую генерацию DDL-скриптов

# Налаштування для профілю prod
---
spring:
  config:
    activate:
      on-profile: prod
  sql:
    init:
      mode: always
      data-locations: classpath:data-postgres.sql
      schema-locations: classpath:schema-postgres.sql
  datasource:
    url: jdbc:mysql://localhost:3306/bankproject
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      id:
        new_generator_mappings: true
      ddl-auto: none